// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts"
// @generated from file backend.proto (package backend, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "./common_pb.ts";

/**
 * Describes the file backend.proto.
 */
export const file_backend: GenFile = /*@__PURE__*/
  fileDesc("Cg1iYWNrZW5kLnByb3RvEgdiYWNrZW5kQhdaFXBhbmVsaXVtL3Byb3RvLWdlbi1nb2IGcHJvdG8z", [file_common]);

