"use strict";
// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts"
// @generated from file backend.proto (syntax proto2)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.file_backend = void 0;
var codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
var common_pb_ts_1 = require("./common_pb.ts");
/**
 * Describes the file backend.proto.
 */
exports.file_backend = (0, codegenv2_1.fileDesc)("Cg1iYWNrZW5kLnByb3RvQhdaFXBhbmVsaXVtL3Byb3RvLWdlbi1nbw", [common_pb_ts_1.file_common]);
