// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts,js_import_style=module"
// @generated from file backend.proto (package backend, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "./common_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file backend.proto.
 */
export const file_backend: GenFile = /*@__PURE__*/
  fileDesc("Cg1iYWNrZW5kLnByb3RvEgdiYWNrZW5kIkQKD1JlZ2lzdGVyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRINCgVlbWFpbBgCIAEoCRIQCghwYXNzd29yZBgDIAEoCSIjChBSZWdpc3RlclJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiMgoMTG9naW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJImUKDUxvZ2luUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIUCgxyZXF1aXJlc19tZmEYAiABKAgSLQoTbWZhX3R5cGVzX2F2YWlsYWJsZRgDIAMoDjIQLmJhY2tlbmQuTUZBVHlwZSI7ChVSZXF1ZXN0TUZBQ29kZVJlcXVlc3QSIgoIbWZhX3R5cGUYAiABKA4yEC5iYWNrZW5kLk1GQVR5cGUiKQoWUmVxdWVzdE1GQUNvZGVSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIiQKEFZlcmlmeU1GQVJlcXVlc3QSEAoIbWZhX2NvZGUYASABKAkidAoRVmVyaWZ5TUZBUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIfChdyZXF1aXJlc19hZGRpdGlvbmFsX21mYRgCIAEoCBItChNtZmFfdHlwZXNfYXZhaWxhYmxlGAMgAygOMhAuYmFja2VuZC5NRkFUeXBlIhUKE1JlZnJlc2hUb2tlblJlcXVlc3QiJwoUUmVmcmVzaFRva2VuUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCCIPCg1Mb2dvdXRSZXF1ZXN0IiEKDkxvZ291dFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgqXAoHTUZBVHlwZRIYChRNRkFfVFlQRV9VTlNQRUNJRklFRBAAEhEKDU1GQV9UWVBFX1RPVFAQARIQCgxNRkFfVFlQRV9TTVMQAhISCg5NRkFfVFlQRV9FTUFJTBADMrEDCgtBdXRoU2VydmljZRJBCghSZWdpc3RlchIYLmJhY2tlbmQuUmVnaXN0ZXJSZXF1ZXN0GhkuYmFja2VuZC5SZWdpc3RlclJlc3BvbnNlIgASOAoFTG9naW4SFS5iYWNrZW5kLkxvZ2luUmVxdWVzdBoWLmJhY2tlbmQuTG9naW5SZXNwb25zZSIAElMKDlJlcXVlc3RNRkFDb2RlEh4uYmFja2VuZC5SZXF1ZXN0TUZBQ29kZVJlcXVlc3QaHy5iYWNrZW5kLlJlcXVlc3RNRkFDb2RlUmVzcG9uc2UiABJECglWZXJpZnlNRkESGS5iYWNrZW5kLlZlcmlmeU1GQVJlcXVlc3QaGi5iYWNrZW5kLlZlcmlmeU1GQVJlc3BvbnNlIgASTQoMUmVmcmVzaFRva2VuEhwuYmFja2VuZC5SZWZyZXNoVG9rZW5SZXF1ZXN0Gh0uYmFja2VuZC5SZWZyZXNoVG9rZW5SZXNwb25zZSIAEjsKBkxvZ291dBIWLmJhY2tlbmQuTG9nb3V0UmVxdWVzdBoXLmJhY2tlbmQuTG9nb3V0UmVzcG9uc2UiAEIXWhVwYW5lbGl1bS9wcm90by1nZW4tZ29iBnByb3RvMw", [file_common]);

/**
 * @generated from message backend.RegisterRequest
 */
export type RegisterRequest = Message<"backend.RegisterRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message backend.RegisterRequest.
 * Use `create(RegisterRequestSchema)` to create a new message.
 */
export const RegisterRequestSchema: GenMessage<RegisterRequest> = /*@__PURE__*/
  messageDesc(file_backend, 0);

/**
 * @generated from message backend.RegisterResponse
 */
export type RegisterResponse = Message<"backend.RegisterResponse"> & {
  /**
   * COOKIES
   * access_jwt (if register success)
   * refresh_jwt (if register success)
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend.RegisterResponse.
 * Use `create(RegisterResponseSchema)` to create a new message.
 */
export const RegisterResponseSchema: GenMessage<RegisterResponse> = /*@__PURE__*/
  messageDesc(file_backend, 1);

/**
 * @generated from message backend.LoginRequest
 */
export type LoginRequest = Message<"backend.LoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message backend.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_backend, 2);

/**
 * @generated from message backend.LoginResponse
 */
export type LoginResponse = Message<"backend.LoginResponse"> & {
  /**
   * COOKIES
   * access_jwt (if auth success and mfa not required)
   * refresh_jwt (if auth success and mfa not required)
   * mfa_jwt (if auth success and mfa required)
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: bool requires_mfa = 2;
   */
  requiresMfa: boolean;

  /**
   * (optional) types of MFA available for the user
   *
   * @generated from field: repeated backend.MFAType mfa_types_available = 3;
   */
  mfaTypesAvailable: MFAType[];
};

/**
 * Describes the message backend.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_backend, 3);

/**
 * only for MFA types that require the backend to send a code (e.g. SMS, Email)
 *
 * @generated from message backend.RequestMFACodeRequest
 */
export type RequestMFACodeRequest = Message<"backend.RequestMFACodeRequest"> & {
  /**
   * REQUEST COOKIES
   * mfa_jwt
   *
   * type of MFA to use
   *
   * @generated from field: backend.MFAType mfa_type = 2;
   */
  mfaType: MFAType;
};

/**
 * Describes the message backend.RequestMFACodeRequest.
 * Use `create(RequestMFACodeRequestSchema)` to create a new message.
 */
export const RequestMFACodeRequestSchema: GenMessage<RequestMFACodeRequest> = /*@__PURE__*/
  messageDesc(file_backend, 4);

/**
 * @generated from message backend.RequestMFACodeResponse
 */
export type RequestMFACodeResponse = Message<"backend.RequestMFACodeResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend.RequestMFACodeResponse.
 * Use `create(RequestMFACodeResponseSchema)` to create a new message.
 */
export const RequestMFACodeResponseSchema: GenMessage<RequestMFACodeResponse> = /*@__PURE__*/
  messageDesc(file_backend, 5);

/**
 * @generated from message backend.VerifyMFARequest
 */
export type VerifyMFARequest = Message<"backend.VerifyMFARequest"> & {
  /**
   * REQUEST COOKIES
   * mfa_jwt
   *
   * @generated from field: string mfa_code = 1;
   */
  mfaCode: string;
};

/**
 * Describes the message backend.VerifyMFARequest.
 * Use `create(VerifyMFARequestSchema)` to create a new message.
 */
export const VerifyMFARequestSchema: GenMessage<VerifyMFARequest> = /*@__PURE__*/
  messageDesc(file_backend, 6);

/**
 * @generated from message backend.VerifyMFAResponse
 */
export type VerifyMFAResponse = Message<"backend.VerifyMFAResponse"> & {
  /**
   * COOKIES
   * access_jwt (if auth and MFA success and no additional MFA required)
   * refresh_jwt (if auth and MFA success and no additional MFA required)
   * mfa_jwt (if auth and MFA success but additional MFA required)
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;

  /**
   * @generated from field: bool requires_additional_mfa = 2;
   */
  requiresAdditionalMfa: boolean;

  /**
   * @generated from field: repeated backend.MFAType mfa_types_available = 3;
   */
  mfaTypesAvailable: MFAType[];
};

/**
 * Describes the message backend.VerifyMFAResponse.
 * Use `create(VerifyMFAResponseSchema)` to create a new message.
 */
export const VerifyMFAResponseSchema: GenMessage<VerifyMFAResponse> = /*@__PURE__*/
  messageDesc(file_backend, 7);

/**
 * REQUEST COOKIES
 * refresh_jwt
 *
 * @generated from message backend.RefreshTokenRequest
 */
export type RefreshTokenRequest = Message<"backend.RefreshTokenRequest"> & {
};

/**
 * Describes the message backend.RefreshTokenRequest.
 * Use `create(RefreshTokenRequestSchema)` to create a new message.
 */
export const RefreshTokenRequestSchema: GenMessage<RefreshTokenRequest> = /*@__PURE__*/
  messageDesc(file_backend, 8);

/**
 * note: if refresh token reuse - revoke all user tokens
 *
 * @generated from message backend.RefreshTokenResponse
 */
export type RefreshTokenResponse = Message<"backend.RefreshTokenResponse"> & {
  /**
   * COOKIES
   * access_jwt (if refresh token valid)
   * refresh_jwt (if refresh token valid)
   *
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend.RefreshTokenResponse.
 * Use `create(RefreshTokenResponseSchema)` to create a new message.
 */
export const RefreshTokenResponseSchema: GenMessage<RefreshTokenResponse> = /*@__PURE__*/
  messageDesc(file_backend, 9);

/**
 * REQUEST COOKIES
 * access_jwt
 *
 * @generated from message backend.LogoutRequest
 */
export type LogoutRequest = Message<"backend.LogoutRequest"> & {
};

/**
 * Describes the message backend.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_backend, 10);

/**
 * @generated from message backend.LogoutResponse
 */
export type LogoutResponse = Message<"backend.LogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_backend, 11);

/**
 * @generated from enum backend.MFAType
 */
export enum MFAType {
  /**
   * @generated from enum value: MFA_TYPE_UNSPECIFIED = 0;
   */
  MFA_TYPE_UNSPECIFIED = 0,

  /**
   * @generated from enum value: MFA_TYPE_TOTP = 1;
   */
  MFA_TYPE_TOTP = 1,

  /**
   * @generated from enum value: MFA_TYPE_SMS = 2;
   */
  MFA_TYPE_SMS = 2,

  /**
   * @generated from enum value: MFA_TYPE_EMAIL = 3;
   */
  MFA_TYPE_EMAIL = 3,
}

/**
 * Describes the enum backend.MFAType.
 */
export const MFATypeSchema: GenEnum<MFAType> = /*@__PURE__*/
  enumDesc(file_backend, 0);

/**
 * @generated from service backend.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc backend.AuthService.Register
   */
  register: {
    methodKind: "unary";
    input: typeof RegisterRequestSchema;
    output: typeof RegisterResponseSchema;
  },
  /**
   * @generated from rpc backend.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc backend.AuthService.RequestMFACode
   */
  requestMFACode: {
    methodKind: "unary";
    input: typeof RequestMFACodeRequestSchema;
    output: typeof RequestMFACodeResponseSchema;
  },
  /**
   * @generated from rpc backend.AuthService.VerifyMFA
   */
  verifyMFA: {
    methodKind: "unary";
    input: typeof VerifyMFARequestSchema;
    output: typeof VerifyMFAResponseSchema;
  },
  /**
   * @generated from rpc backend.AuthService.RefreshToken
   */
  refreshToken: {
    methodKind: "unary";
    input: typeof RefreshTokenRequestSchema;
    output: typeof RefreshTokenResponseSchema;
  },
  /**
   * @generated from rpc backend.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_backend, 0);

