// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts,js_import_style=module"
// @generated from file common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SBmNvbW1vbiIHCgVFbXB0eSIdCg1TaW1wbGVNZXNzYWdlEgwKBHRleHQYASABKAkiIQoOU3VjY2Vzc01lc3NhZ2USDwoHc3VjY2VzcxgBIAEoCEIXWhVwYW5lbGl1bS9wcm90by1nZW4tZ29iBnByb3RvMw");

/**
 * @generated from message common.Empty
 */
export type Empty = Message<"common.Empty"> & {
};

/**
 * Describes the message common.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * @generated from message common.SimpleMessage
 */
export type SimpleMessage = Message<"common.SimpleMessage"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message common.SimpleMessage.
 * Use `create(SimpleMessageSchema)` to create a new message.
 */
export const SimpleMessageSchema: GenMessage<SimpleMessage> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * @generated from message common.SuccessMessage
 */
export type SuccessMessage = Message<"common.SuccessMessage"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message common.SuccessMessage.
 * Use `create(SuccessMessageSchema)` to create a new message.
 */
export const SuccessMessageSchema: GenMessage<SuccessMessage> = /*@__PURE__*/
  messageDesc(file_common, 2);

