// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common.proto.
 */
export const file_common: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb21tb24ucHJvdG8SBmNvbW1vbiIHCgVFbXB0eSIdCg9TaW1wbGVJRE1lc3NhZ2USCgoCaWQYASABKAkiJQoJSURNZXNzYWdlEgoKAmlkGAEgASgJEgwKBHRleHQYAiABKAkiRQoPU3RyZWFtSURNZXNzYWdlEg8KAmlkGAEgASgJSACIAQESEQoEdGV4dBgCIAEoCUgBiAEBQgUKA19pZEIHCgVfdGV4dCIdCg1TaW1wbGVNZXNzYWdlEgwKBHRleHQYASABKAkiIQoOU3VjY2Vzc01lc3NhZ2USDwoHc3VjY2VzcxgBIAEoCCJICg1SZXNvdXJjZUxpbWl0EgsKA2NwdRgBIAEoDRILCgNyYW0YAiABKA0SDAoEc3dhcBgDIAEoDRIPCgdzdG9yYWdlGAQgASgNIigKDElQQWxsb2NhdGlvbhIKCgJpcBgBIAEoCRIMCgRwb3J0GAIgASgNQhdaFXBhbmVsaXVtL3Byb3RvX2dlbl9nb2IGcHJvdG8z");

/**
 * @generated from message common.Empty
 */
export type Empty = Message<"common.Empty"> & {
};

/**
 * Describes the message common.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export const EmptySchema: GenMessage<Empty> = /*@__PURE__*/
  messageDesc(file_common, 0);

/**
 * @generated from message common.SimpleIDMessage
 */
export type SimpleIDMessage = Message<"common.SimpleIDMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message common.SimpleIDMessage.
 * Use `create(SimpleIDMessageSchema)` to create a new message.
 */
export const SimpleIDMessageSchema: GenMessage<SimpleIDMessage> = /*@__PURE__*/
  messageDesc(file_common, 1);

/**
 * @generated from message common.IDMessage
 */
export type IDMessage = Message<"common.IDMessage"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message common.IDMessage.
 * Use `create(IDMessageSchema)` to create a new message.
 */
export const IDMessageSchema: GenMessage<IDMessage> = /*@__PURE__*/
  messageDesc(file_common, 2);

/**
 * @generated from message common.StreamIDMessage
 */
export type StreamIDMessage = Message<"common.StreamIDMessage"> & {
  /**
   * only required for the first message in the stream, subsequent messages can omit this field
   *
   * @generated from field: optional string id = 1;
   */
  id?: string;

  /**
   * required after the first message in the stream, first message can omit this field
   *
   * @generated from field: optional string text = 2;
   */
  text?: string;
};

/**
 * Describes the message common.StreamIDMessage.
 * Use `create(StreamIDMessageSchema)` to create a new message.
 */
export const StreamIDMessageSchema: GenMessage<StreamIDMessage> = /*@__PURE__*/
  messageDesc(file_common, 3);

/**
 * @generated from message common.SimpleMessage
 */
export type SimpleMessage = Message<"common.SimpleMessage"> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message common.SimpleMessage.
 * Use `create(SimpleMessageSchema)` to create a new message.
 */
export const SimpleMessageSchema: GenMessage<SimpleMessage> = /*@__PURE__*/
  messageDesc(file_common, 4);

/**
 * @generated from message common.SuccessMessage
 */
export type SuccessMessage = Message<"common.SuccessMessage"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message common.SuccessMessage.
 * Use `create(SuccessMessageSchema)` to create a new message.
 */
export const SuccessMessageSchema: GenMessage<SuccessMessage> = /*@__PURE__*/
  messageDesc(file_common, 5);

/**
 * @generated from message common.ResourceLimit
 */
export type ResourceLimit = Message<"common.ResourceLimit"> & {
  /**
   * CPU in percentage (100% = 1 vCore)
   *
   * @generated from field: uint32 cpu = 1;
   */
  cpu: number;

  /**
   * RAM in MB
   *
   * @generated from field: uint32 ram = 2;
   */
  ram: number;

  /**
   * SWAP in MB
   *
   * @generated from field: uint32 swap = 3;
   */
  swap: number;

  /**
   * Storage in MB
   *
   * @generated from field: uint32 storage = 4;
   */
  storage: number;
};

/**
 * Describes the message common.ResourceLimit.
 * Use `create(ResourceLimitSchema)` to create a new message.
 */
export const ResourceLimitSchema: GenMessage<ResourceLimit> = /*@__PURE__*/
  messageDesc(file_common, 6);

/**
 * @generated from message common.IPAllocation
 */
export type IPAllocation = Message<"common.IPAllocation"> & {
  /**
   * @generated from field: string ip = 1;
   */
  ip: string;

  /**
   * MUST BE 1024-65535
   *
   * @generated from field: uint32 port = 2;
   */
  port: number;
};

/**
 * Describes the message common.IPAllocation.
 * Use `create(IPAllocationSchema)` to create a new message.
 */
export const IPAllocationSchema: GenMessage<IPAllocation> = /*@__PURE__*/
  messageDesc(file_common, 7);

