"use strict";
// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts"
// @generated from file common.proto (syntax proto2)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleMessageSchema = exports.EmptySchema = exports.file_common = void 0;
var codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file common.proto.
 */
exports.file_common = (0, codegenv2_1.fileDesc)("Cgxjb21tb24ucHJvdG8iBwoFRW1wdHkiHQoNU2ltcGxlTWVzc2FnZRIMCgR0ZXh0GAEgAigJQhdaFXBhbmVsaXVtL3Byb3RvLWdlbi1nbw");
/**
 * Describes the message Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
exports.EmptySchema = (0, codegenv2_1.messageDesc)(exports.file_common, 0);
/**
 * Describes the message SimpleMessage.
 * Use `create(SimpleMessageSchema)` to create a new message.
 */
exports.SimpleMessageSchema = (0, codegenv2_1.messageDesc)(exports.file_common, 1);
