"use strict";
// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts"
// @generated from file common.proto (package common, syntax proto3)
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SimpleMessageSchema = exports.EmptySchema = exports.file_common = void 0;
var codegenv2_1 = require("@bufbuild/protobuf/codegenv2");
/**
 * Describes the file common.proto.
 */
exports.file_common = (0, codegenv2_1.fileDesc)("Cgxjb21tb24ucHJvdG8SBmNvbW1vbiIHCgVFbXB0eSIdCg1TaW1wbGVNZXNzYWdlEgwKBHRleHQYASABKAlCF1oVcGFuZWxpdW0vcHJvdG8tZ2VuLWdvYgZwcm90bzM");
/**
 * Describes the message common.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
exports.EmptySchema = (0, codegenv2_1.messageDesc)(exports.file_common, 0);
/**
 * Describes the message common.SimpleMessage.
 * Use `create(SimpleMessageSchema)` to create a new message.
 */
exports.SimpleMessageSchema = (0, codegenv2_1.messageDesc)(exports.file_common, 1);
