// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts"
// @generated from file daemon.proto (syntax proto2)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "./common_pb.ts";

/**
 * Describes the file daemon.proto.
 */
export const file_daemon: GenFile = /*@__PURE__*/
  fileDesc("CgxkYWVtb24ucHJvdG9CF1oVcGFuZWxpdW0vcHJvdG8tZ2VuLWdv", [file_common]);

