// @generated by protoc-gen-es v2.5.0
// @generated from file daemon.proto (syntax proto2)
/* eslint-disable */

import { fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file daemon.proto.
 */
export const file_daemon = /*@__PURE__*/
  fileDesc("CgxkYWVtb24ucHJvdG9CF1oVcGFuZWxpdW0vcHJvdG8tZ2VuLWdv");

