// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=ts,js_import_style=module"
// @generated from file daemon_Server.proto (package daemon, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { EmptySchema, SimpleMessageSchema, SuccessMessageSchema } from "./common_pb.ts";
import { file_common } from "./common_pb.ts";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file daemon_Server.proto.
 */
export const file_daemon_Server: GenFile = /*@__PURE__*/
  fileDesc("ChNkYWVtb25fU2VydmVyLnByb3RvEgZkYWVtb24ilwIKDFNlcnZlclN0YXR1cxIoCgZzdGF0dXMYASABKA4yGC5kYWVtb24uU2VydmVyU3RhdHVzVHlwZRI3Cg50aW1lc3RhbXBTdGFydBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBIAIgBARI1Cgx0aW1lc3RhbXBFbmQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wSAGIAQESNwoNb2ZmbGluZVJlYXNvbhgEIAEoDjIbLmRhZW1vbi5TZXJ2ZXJPZmZsaW5lUmVhc29uSAKIAQFCEQoPX3RpbWVzdGFtcFN0YXJ0Qg8KDV90aW1lc3RhbXBFbmRCEAoOX29mZmxpbmVSZWFzb24qswEKEFNlcnZlclN0YXR1c1R5cGUSHgoaU0VSVkVSX1NUQVRVU19UWVBFX1VOS05PV04QABIfChtTRVJWRVJfU1RBVFVTX1RZUEVfU1RBUlRJTkcQARIdChlTRVJWRVJfU1RBVFVTX1RZUEVfT05MSU5FEAISHwobU0VSVkVSX1NUQVRVU19UWVBFX1NUT1BQSU5HEAMSHgoaU0VSVkVSX1NUQVRVU19UWVBFX09GRkxJTkUQBCrBAQoTU2VydmVyT2ZmbGluZVJlYXNvbhIhCh1TRVJWRVJfT0ZGTElORV9SRUFTT05fVU5LTk9XThAAEiEKHVNFUlZFUl9PRkZMSU5FX1JFQVNPTl9DUkVBVEVEEAESIQodU0VSVkVSX09GRkxJTkVfUkVBU09OX1NUT1BQRUQQAhIgChxTRVJWRVJfT0ZGTElORV9SRUFTT05fS0lMTEVEEAMSHwobU0VSVkVSX09GRkxJTkVfUkVBU09OX0VSUk9SEAQqiwEKC1Bvd2VyQWN0aW9uEhwKGFBPV0VSX0FDVElPTl9VTlNQRUNJRklFRBAAEhYKElBPV0VSX0FDVElPTl9TVEFSVBABEhgKFFBPV0VSX0FDVElPTl9SRVNUQVJUEAISFQoRUE9XRVJfQUNUSU9OX1NUT1AQAxIVChFQT1dFUl9BQ1RJT05fS0lMTBAEMvwCCg1TZXJ2ZXJTZXJ2aWNlEjsKB0NvbnNvbGUSFS5jb21tb24uU2ltcGxlTWVzc2FnZRoVLmNvbW1vbi5TaW1wbGVNZXNzYWdlKAEwARI7CgpSdW5Db21tYW5kEhUuY29tbW9uLlNpbXBsZU1lc3NhZ2UaFi5jb21tb24uU3VjY2Vzc01lc3NhZ2USPAoIVGVybWluYWwSFS5jb21tb24uU2ltcGxlTWVzc2FnZRoVLmNvbW1vbi5TaW1wbGVNZXNzYWdlKAEwARJDChJSdW5UZXJtaW5hbENvbW1hbmQSFS5jb21tb24uU2ltcGxlTWVzc2FnZRoWLmNvbW1vbi5TdWNjZXNzTWVzc2FnZRIwCglHZXRTdGF0dXMSDS5jb21tb24uRW1wdHkaFC5kYWVtb24uU2VydmVyU3RhdHVzEjwKC1Bvd2VyQWN0aW9uEhUuY29tbW9uLlNpbXBsZU1lc3NhZ2UaFi5jb21tb24uU3VjY2Vzc01lc3NhZ2VCF1oVcGFuZWxpdW0vcHJvdG8tZ2VuLWdvYgZwcm90bzM", [file_common, file_google_protobuf_timestamp]);

/**
 * Server Info
 *
 * @generated from message daemon.ServerStatus
 */
export type ServerStatus = Message<"daemon.ServerStatus"> & {
  /**
   * @generated from field: daemon.ServerStatusType status = 1;
   */
  status: ServerStatusType;

  /**
   * @generated from field: optional google.protobuf.Timestamp timestampStart = 2;
   */
  timestampStart?: Timestamp;

  /**
   * @generated from field: optional google.protobuf.Timestamp timestampEnd = 3;
   */
  timestampEnd?: Timestamp;

  /**
   * @generated from field: optional daemon.ServerOfflineReason offlineReason = 4;
   */
  offlineReason?: ServerOfflineReason;
};

/**
 * Describes the message daemon.ServerStatus.
 * Use `create(ServerStatusSchema)` to create a new message.
 */
export const ServerStatusSchema: GenMessage<ServerStatus> = /*@__PURE__*/
  messageDesc(file_daemon_Server, 0);

/**
 * @generated from enum daemon.ServerStatusType
 */
export enum ServerStatusType {
  /**
   * @generated from enum value: SERVER_STATUS_TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: SERVER_STATUS_TYPE_STARTING = 1;
   */
  STARTING = 1,

  /**
   * @generated from enum value: SERVER_STATUS_TYPE_ONLINE = 2;
   */
  ONLINE = 2,

  /**
   * @generated from enum value: SERVER_STATUS_TYPE_STOPPING = 3;
   */
  STOPPING = 3,

  /**
   * @generated from enum value: SERVER_STATUS_TYPE_OFFLINE = 4;
   */
  OFFLINE = 4,
}

/**
 * Describes the enum daemon.ServerStatusType.
 */
export const ServerStatusTypeSchema: GenEnum<ServerStatusType> = /*@__PURE__*/
  enumDesc(file_daemon_Server, 0);

/**
 * @generated from enum daemon.ServerOfflineReason
 */
export enum ServerOfflineReason {
  /**
   * @generated from enum value: SERVER_OFFLINE_REASON_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: SERVER_OFFLINE_REASON_CREATED = 1;
   */
  CREATED = 1,

  /**
   * @generated from enum value: SERVER_OFFLINE_REASON_STOPPED = 2;
   */
  STOPPED = 2,

  /**
   * @generated from enum value: SERVER_OFFLINE_REASON_KILLED = 3;
   */
  KILLED = 3,

  /**
   * @generated from enum value: SERVER_OFFLINE_REASON_ERROR = 4;
   */
  ERROR = 4,
}

/**
 * Describes the enum daemon.ServerOfflineReason.
 */
export const ServerOfflineReasonSchema: GenEnum<ServerOfflineReason> = /*@__PURE__*/
  enumDesc(file_daemon_Server, 1);

/**
 * Power Actions
 *
 * @generated from enum daemon.PowerAction
 */
export enum PowerAction {
  /**
   * Default value, should not be used
   *
   * @generated from enum value: POWER_ACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POWER_ACTION_START = 1;
   */
  START = 1,

  /**
   * @generated from enum value: POWER_ACTION_RESTART = 2;
   */
  RESTART = 2,

  /**
   * @generated from enum value: POWER_ACTION_STOP = 3;
   */
  STOP = 3,

  /**
   * @generated from enum value: POWER_ACTION_KILL = 4;
   */
  KILL = 4,
}

/**
 * Describes the enum daemon.PowerAction.
 */
export const PowerActionSchema: GenEnum<PowerAction> = /*@__PURE__*/
  enumDesc(file_daemon_Server, 2);

/**
 * @generated from service daemon.ServerService
 */
export const ServerService: GenService<{
  /**
   * Console (process)
   *
   * @generated from rpc daemon.ServerService.Console
   */
  console: {
    methodKind: "bidi_streaming";
    input: typeof SimpleMessageSchema;
    output: typeof SimpleMessageSchema;
  },
  /**
   * @generated from rpc daemon.ServerService.RunCommand
   */
  runCommand: {
    methodKind: "unary";
    input: typeof SimpleMessageSchema;
    output: typeof SuccessMessageSchema;
  },
  /**
   * Terminal (system)
   *
   * @generated from rpc daemon.ServerService.Terminal
   */
  terminal: {
    methodKind: "bidi_streaming";
    input: typeof SimpleMessageSchema;
    output: typeof SimpleMessageSchema;
  },
  /**
   * @generated from rpc daemon.ServerService.RunTerminalCommand
   */
  runTerminalCommand: {
    methodKind: "unary";
    input: typeof SimpleMessageSchema;
    output: typeof SuccessMessageSchema;
  },
  /**
   * Server Info
   *
   * @generated from rpc daemon.ServerService.GetStatus
   */
  getStatus: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof ServerStatusSchema;
  },
  /**
   * Power Actions
   *
   * @generated from rpc daemon.ServerService.PowerAction
   */
  powerAction: {
    methodKind: "unary";
    input: typeof SimpleMessageSchema;
    output: typeof SuccessMessageSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_daemon_Server, 0);

