// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/Blueprint.proto (package backend, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "../common_pb";

/**
 * Describes the file backend/Blueprint.proto.
 */
export const file_backend_Blueprint: GenFile = /*@__PURE__*/
  fileDesc("ChdiYWNrZW5kL0JsdWVwcmludC5wcm90bxIHYmFja2VuZDISChBCbHVlcHJpbnRTZXJ2aWNlQh9aHXBhbmVsaXVtL3Byb3RvX2dlbl9nby9iYWNrZW5kYgZwcm90bzM", [file_common]);

/**
 * @generated from service backend.BlueprintService
 */
export const BlueprintService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_backend_Blueprint, 0);

