// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/DaemonConnection.proto (package backend, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { SimpleIDMessageSchema, SuccessMessageSchema } from "../common_pb";
import { file_common } from "../common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file backend/DaemonConnection.proto.
 */
export const file_backend_DaemonConnection: GenFile = /*@__PURE__*/
  fileDesc("Ch5iYWNrZW5kL0RhZW1vbkNvbm5lY3Rpb24ucHJvdG8SB2JhY2tlbmQiLAoTQ3JlYXRlVG9rZW5SZXNwb25zZRIVCg1iYWNrZW5kX3Rva2VuGAEgASgJIkIKFVJlZ2lzdGVyRGFlbW9uUmVxdWVzdBIVCg1iYWNrZW5kX3Rva2VuGAEgASgJEhIKCm5vZGVfdG9rZW4YAiABKAkysAEKF0RhZW1vbkNvbm5lY3Rpb25TZXJ2aWNlEksKEkNyZWF0ZUJhY2tlbmRUb2tlbhIXLmNvbW1vbi5TaW1wbGVJRE1lc3NhZ2UaHC5iYWNrZW5kLkNyZWF0ZVRva2VuUmVzcG9uc2USSAoOUmVnaXN0ZXJEYWVtb24SHi5iYWNrZW5kLlJlZ2lzdGVyRGFlbW9uUmVxdWVzdBoWLmNvbW1vbi5TdWNjZXNzTWVzc2FnZUIfWh1wYW5lbGl1bS9wcm90b19nZW5fZ28vYmFja2VuZGIGcHJvdG8z", [file_common]);

/**
 * @generated from message backend.CreateTokenResponse
 */
export type CreateTokenResponse = Message<"backend.CreateTokenResponse"> & {
  /**
   * @generated from field: string backend_token = 1;
   */
  backendToken: string;
};

/**
 * Describes the message backend.CreateTokenResponse.
 * Use `create(CreateTokenResponseSchema)` to create a new message.
 */
export const CreateTokenResponseSchema: GenMessage<CreateTokenResponse> = /*@__PURE__*/
  messageDesc(file_backend_DaemonConnection, 0);

/**
 * @generated from message backend.RegisterDaemonRequest
 */
export type RegisterDaemonRequest = Message<"backend.RegisterDaemonRequest"> & {
  /**
   * @generated from field: string backend_token = 1;
   */
  backendToken: string;

  /**
   * @generated from field: string node_token = 2;
   */
  nodeToken: string;
};

/**
 * Describes the message backend.RegisterDaemonRequest.
 * Use `create(RegisterDaemonRequestSchema)` to create a new message.
 */
export const RegisterDaemonRequestSchema: GenMessage<RegisterDaemonRequest> = /*@__PURE__*/
  messageDesc(file_backend_DaemonConnection, 1);

/**
 * @generated from service backend.DaemonConnectionService
 */
export const DaemonConnectionService: GenService<{
  /**
   * @generated from rpc backend.DaemonConnectionService.CreateBackendToken
   */
  createBackendToken: {
    methodKind: "unary";
    input: typeof SimpleIDMessageSchema;
    output: typeof CreateTokenResponseSchema;
  },
  /**
   * @generated from rpc backend.DaemonConnectionService.RegisterDaemon
   */
  registerDaemon: {
    methodKind: "unary";
    input: typeof RegisterDaemonRequestSchema;
    output: typeof SuccessMessageSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_backend_DaemonConnection, 0);

