// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/Users.proto (package backend, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "../common_pb";

/**
 * Describes the file backend/Users.proto.
 */
export const file_backend_Users: GenFile = /*@__PURE__*/
  fileDesc("ChNiYWNrZW5kL1VzZXJzLnByb3RvEgdiYWNrZW5kMg4KDFVzZXJzU2VydmljZUIfWh1wYW5lbGl1bS9wcm90b19nZW5fZ28vYmFja2VuZGIGcHJvdG8z", [file_common]);

/**
 * @generated from service backend.UsersService
 */
export const UsersService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_backend_Users, 0);

