// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/admin/BlueprintManager.proto (package backend_admin, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "../../common_pb";

/**
 * Describes the file backend/admin/BlueprintManager.proto.
 */
export const file_backend_admin_BlueprintManager: GenFile = /*@__PURE__*/
  fileDesc("CiRiYWNrZW5kL2FkbWluL0JsdWVwcmludE1hbmFnZXIucHJvdG8SDWJhY2tlbmRfYWRtaW5CJVojcGFuZWxpdW0vcHJvdG9fZ2VuX2dvL2JhY2tlbmQvYWRtaW5iBnByb3RvMw", [file_common]);

