// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/admin/LocationManager.proto (package backend_admin, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "../../common_pb";

/**
 * Describes the file backend/admin/LocationManager.proto.
 */
export const file_backend_admin_LocationManager: GenFile = /*@__PURE__*/
  fileDesc("CiNiYWNrZW5kL2FkbWluL0xvY2F0aW9uTWFuYWdlci5wcm90bxINYmFja2VuZF9hZG1pbkIlWiNwYW5lbGl1bS9wcm90b19nZW5fZ28vYmFja2VuZC9hZG1pbmIGcHJvdG8z", [file_common]);

