// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/admin/LocationManager.proto (package backend_admin, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Pagination } from "../../common_pb";
import { file_common } from "../../common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file backend/admin/LocationManager.proto.
 */
export const file_backend_admin_LocationManager: GenFile = /*@__PURE__*/
  fileDesc("CiNiYWNrZW5kL2FkbWluL0xvY2F0aW9uTWFuYWdlci5wcm90bxINYmFja2VuZF9hZG1pbiIlCghMb2NhdGlvbhILCgNsaWQYASABKAkSDAoEbmFtZRgCIAEoCSI9ChNHZXRMb2NhdGlvbnNSZXF1ZXN0EiYKCnBhZ2luYXRpb24YASABKAsyEi5jb21tb24uUGFnaW5hdGlvbiJqChRHZXRMb2NhdGlvbnNSZXNwb25zZRIqCglsb2NhdGlvbnMYASADKAsyFy5iYWNrZW5kX2FkbWluLkxvY2F0aW9uEiYKCnBhZ2luYXRpb24YAiABKAsyEi5jb21tb24uUGFnaW5hdGlvbiIhChJHZXRMb2NhdGlvblJlcXVlc3QSCwoDbGlkGAEgASgJIkAKE0dldExvY2F0aW9uUmVzcG9uc2USKQoIbG9jYXRpb24YASABKAsyFy5iYWNrZW5kX2FkbWluLkxvY2F0aW9uIkIKFUNyZWF0ZUxvY2F0aW9uUmVxdWVzdBIpCghsb2NhdGlvbhgBIAEoCzIXLmJhY2tlbmRfYWRtaW4uTG9jYXRpb24iKQoWQ3JlYXRlTG9jYXRpb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIkIKFVVwZGF0ZUxvY2F0aW9uUmVxdWVzdBIpCghsb2NhdGlvbhgBIAEoCzIXLmJhY2tlbmRfYWRtaW4uTG9jYXRpb24iKQoWVXBkYXRlTG9jYXRpb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIiQKFURlbGV0ZUxvY2F0aW9uUmVxdWVzdBILCgNsaWQYASABKAkiKQoWRGVsZXRlTG9jYXRpb25SZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIMuQDChZMb2NhdGlvbk1hbmFnZXJTZXJ2aWNlElcKDEdldExvY2F0aW9ucxIiLmJhY2tlbmRfYWRtaW4uR2V0TG9jYXRpb25zUmVxdWVzdBojLmJhY2tlbmRfYWRtaW4uR2V0TG9jYXRpb25zUmVzcG9uc2USVAoLR2V0TG9jYXRpb24SIS5iYWNrZW5kX2FkbWluLkdldExvY2F0aW9uUmVxdWVzdBoiLmJhY2tlbmRfYWRtaW4uR2V0TG9jYXRpb25SZXNwb25zZRJdCg5DcmVhdGVMb2NhdGlvbhIkLmJhY2tlbmRfYWRtaW4uQ3JlYXRlTG9jYXRpb25SZXF1ZXN0GiUuYmFja2VuZF9hZG1pbi5DcmVhdGVMb2NhdGlvblJlc3BvbnNlEl0KDlVwZGF0ZUxvY2F0aW9uEiQuYmFja2VuZF9hZG1pbi5VcGRhdGVMb2NhdGlvblJlcXVlc3QaJS5iYWNrZW5kX2FkbWluLlVwZGF0ZUxvY2F0aW9uUmVzcG9uc2USXQoORGVsZXRlTG9jYXRpb24SJC5iYWNrZW5kX2FkbWluLkRlbGV0ZUxvY2F0aW9uUmVxdWVzdBolLmJhY2tlbmRfYWRtaW4uRGVsZXRlTG9jYXRpb25SZXNwb25zZUIlWiNwYW5lbGl1bS9wcm90b19nZW5fZ28vYmFja2VuZC9hZG1pbmIGcHJvdG8z", [file_common]);

/**
 * @generated from message backend_admin.Location
 */
export type Location = Message<"backend_admin.Location"> & {
  /**
   * ignored with Create
   *
   * @generated from field: string lid = 1;
   */
  lid: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message backend_admin.Location.
 * Use `create(LocationSchema)` to create a new message.
 */
export const LocationSchema: GenMessage<Location> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 0);

/**
 * @generated from message backend_admin.GetLocationsRequest
 */
export type GetLocationsRequest = Message<"backend_admin.GetLocationsRequest"> & {
  /**
   * @generated from field: common.Pagination pagination = 1;
   */
  pagination?: Pagination;
};

/**
 * Describes the message backend_admin.GetLocationsRequest.
 * Use `create(GetLocationsRequestSchema)` to create a new message.
 */
export const GetLocationsRequestSchema: GenMessage<GetLocationsRequest> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 1);

/**
 * @generated from message backend_admin.GetLocationsResponse
 */
export type GetLocationsResponse = Message<"backend_admin.GetLocationsResponse"> & {
  /**
   * @generated from field: repeated backend_admin.Location locations = 1;
   */
  locations: Location[];

  /**
   * @generated from field: common.Pagination pagination = 2;
   */
  pagination?: Pagination;
};

/**
 * Describes the message backend_admin.GetLocationsResponse.
 * Use `create(GetLocationsResponseSchema)` to create a new message.
 */
export const GetLocationsResponseSchema: GenMessage<GetLocationsResponse> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 2);

/**
 * @generated from message backend_admin.GetLocationRequest
 */
export type GetLocationRequest = Message<"backend_admin.GetLocationRequest"> & {
  /**
   * @generated from field: string lid = 1;
   */
  lid: string;
};

/**
 * Describes the message backend_admin.GetLocationRequest.
 * Use `create(GetLocationRequestSchema)` to create a new message.
 */
export const GetLocationRequestSchema: GenMessage<GetLocationRequest> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 3);

/**
 * @generated from message backend_admin.GetLocationResponse
 */
export type GetLocationResponse = Message<"backend_admin.GetLocationResponse"> & {
  /**
   * @generated from field: backend_admin.Location location = 1;
   */
  location?: Location;
};

/**
 * Describes the message backend_admin.GetLocationResponse.
 * Use `create(GetLocationResponseSchema)` to create a new message.
 */
export const GetLocationResponseSchema: GenMessage<GetLocationResponse> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 4);

/**
 * @generated from message backend_admin.CreateLocationRequest
 */
export type CreateLocationRequest = Message<"backend_admin.CreateLocationRequest"> & {
  /**
   * @generated from field: backend_admin.Location location = 1;
   */
  location?: Location;
};

/**
 * Describes the message backend_admin.CreateLocationRequest.
 * Use `create(CreateLocationRequestSchema)` to create a new message.
 */
export const CreateLocationRequestSchema: GenMessage<CreateLocationRequest> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 5);

/**
 * @generated from message backend_admin.CreateLocationResponse
 */
export type CreateLocationResponse = Message<"backend_admin.CreateLocationResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend_admin.CreateLocationResponse.
 * Use `create(CreateLocationResponseSchema)` to create a new message.
 */
export const CreateLocationResponseSchema: GenMessage<CreateLocationResponse> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 6);

/**
 * @generated from message backend_admin.UpdateLocationRequest
 */
export type UpdateLocationRequest = Message<"backend_admin.UpdateLocationRequest"> & {
  /**
   * @generated from field: backend_admin.Location location = 1;
   */
  location?: Location;
};

/**
 * Describes the message backend_admin.UpdateLocationRequest.
 * Use `create(UpdateLocationRequestSchema)` to create a new message.
 */
export const UpdateLocationRequestSchema: GenMessage<UpdateLocationRequest> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 7);

/**
 * @generated from message backend_admin.UpdateLocationResponse
 */
export type UpdateLocationResponse = Message<"backend_admin.UpdateLocationResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend_admin.UpdateLocationResponse.
 * Use `create(UpdateLocationResponseSchema)` to create a new message.
 */
export const UpdateLocationResponseSchema: GenMessage<UpdateLocationResponse> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 8);

/**
 * @generated from message backend_admin.DeleteLocationRequest
 */
export type DeleteLocationRequest = Message<"backend_admin.DeleteLocationRequest"> & {
  /**
   * @generated from field: string lid = 1;
   */
  lid: string;
};

/**
 * Describes the message backend_admin.DeleteLocationRequest.
 * Use `create(DeleteLocationRequestSchema)` to create a new message.
 */
export const DeleteLocationRequestSchema: GenMessage<DeleteLocationRequest> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 9);

/**
 * @generated from message backend_admin.DeleteLocationResponse
 */
export type DeleteLocationResponse = Message<"backend_admin.DeleteLocationResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message backend_admin.DeleteLocationResponse.
 * Use `create(DeleteLocationResponseSchema)` to create a new message.
 */
export const DeleteLocationResponseSchema: GenMessage<DeleteLocationResponse> = /*@__PURE__*/
  messageDesc(file_backend_admin_LocationManager, 10);

/**
 * @generated from service backend_admin.LocationManagerService
 */
export const LocationManagerService: GenService<{
  /**
   * @generated from rpc backend_admin.LocationManagerService.GetLocations
   */
  getLocations: {
    methodKind: "unary";
    input: typeof GetLocationsRequestSchema;
    output: typeof GetLocationsResponseSchema;
  },
  /**
   * @generated from rpc backend_admin.LocationManagerService.GetLocation
   */
  getLocation: {
    methodKind: "unary";
    input: typeof GetLocationRequestSchema;
    output: typeof GetLocationResponseSchema;
  },
  /**
   * @generated from rpc backend_admin.LocationManagerService.CreateLocation
   */
  createLocation: {
    methodKind: "unary";
    input: typeof CreateLocationRequestSchema;
    output: typeof CreateLocationResponseSchema;
  },
  /**
   * @generated from rpc backend_admin.LocationManagerService.UpdateLocation
   */
  updateLocation: {
    methodKind: "unary";
    input: typeof UpdateLocationRequestSchema;
    output: typeof UpdateLocationResponseSchema;
  },
  /**
   * @generated from rpc backend_admin.LocationManagerService.DeleteLocation
   */
  deleteLocation: {
    methodKind: "unary";
    input: typeof DeleteLocationRequestSchema;
    output: typeof DeleteLocationResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_backend_admin_LocationManager, 0);

