// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file backend/admin/UserManager.proto (package backend_admin, syntax proto3)
/* eslint-disable */

import type { GenFile } from "@bufbuild/protobuf/codegenv2";
import { fileDesc } from "@bufbuild/protobuf/codegenv2";
import { file_common } from "../../common_pb";

/**
 * Describes the file backend/admin/UserManager.proto.
 */
export const file_backend_admin_UserManager: GenFile = /*@__PURE__*/
  fileDesc("Ch9iYWNrZW5kL2FkbWluL1VzZXJNYW5hZ2VyLnByb3RvEg1iYWNrZW5kX2FkbWluQiVaI3BhbmVsaXVtL3Byb3RvX2dlbl9nby9iYWNrZW5kL2FkbWluYgZwcm90bzM", [file_common]);

