// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: backend/Nodes.proto

package backendconnect

import (
	connect "connectrpc.com/connect"
	http "net/http"
	_ "panelium/proto_gen_go/backend"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodesServiceName is the fully-qualified name of the NodesService service.
	NodesServiceName = "backend.NodesService"
)

// NodesServiceClient is a client for the backend.NodesService service.
type NodesServiceClient interface {
}

// NewNodesServiceClient constructs a client for the backend.NodesService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodesServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodesServiceClient {
	return &nodesServiceClient{}
}

// nodesServiceClient implements NodesServiceClient.
type nodesServiceClient struct {
}

// NodesServiceHandler is an implementation of the backend.NodesService service.
type NodesServiceHandler interface {
}

// NewNodesServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodesServiceHandler(svc NodesServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	return "/backend.NodesService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodesServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodesServiceHandler struct{}
