// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: daemon/Backend.proto

package daemonconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	proto_gen_go "panelium/proto_gen_go"
	daemon "panelium/proto_gen_go/daemon"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BackendServiceName is the fully-qualified name of the BackendService service.
	BackendServiceName = "daemon.BackendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BackendServiceCreateServerProcedure is the fully-qualified name of the BackendService's
	// CreateServer RPC.
	BackendServiceCreateServerProcedure = "/daemon.BackendService/CreateServer"
	// BackendServiceUpdateServerProcedure is the fully-qualified name of the BackendService's
	// UpdateServer RPC.
	BackendServiceUpdateServerProcedure = "/daemon.BackendService/UpdateServer"
	// BackendServiceDeleteServerProcedure is the fully-qualified name of the BackendService's
	// DeleteServer RPC.
	BackendServiceDeleteServerProcedure = "/daemon.BackendService/DeleteServer"
)

// BackendServiceClient is a client for the daemon.BackendService service.
type BackendServiceClient interface {
	CreateServer(context.Context, *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error)
	UpdateServer(context.Context, *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error)
	DeleteServer(context.Context, *connect.Request[proto_gen_go.SimpleIDMessage]) (*connect.Response[proto_gen_go.SuccessMessage], error)
}

// NewBackendServiceClient constructs a client for the daemon.BackendService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backendServiceMethods := daemon.File_daemon_Backend_proto.Services().ByName("BackendService").Methods()
	return &backendServiceClient{
		createServer: connect.NewClient[daemon.Server, proto_gen_go.SuccessMessage](
			httpClient,
			baseURL+BackendServiceCreateServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CreateServer")),
			connect.WithClientOptions(opts...),
		),
		updateServer: connect.NewClient[daemon.Server, proto_gen_go.SuccessMessage](
			httpClient,
			baseURL+BackendServiceUpdateServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("UpdateServer")),
			connect.WithClientOptions(opts...),
		),
		deleteServer: connect.NewClient[proto_gen_go.SimpleIDMessage, proto_gen_go.SuccessMessage](
			httpClient,
			baseURL+BackendServiceDeleteServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("DeleteServer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backendServiceClient implements BackendServiceClient.
type backendServiceClient struct {
	createServer *connect.Client[daemon.Server, proto_gen_go.SuccessMessage]
	updateServer *connect.Client[daemon.Server, proto_gen_go.SuccessMessage]
	deleteServer *connect.Client[proto_gen_go.SimpleIDMessage, proto_gen_go.SuccessMessage]
}

// CreateServer calls daemon.BackendService.CreateServer.
func (c *backendServiceClient) CreateServer(ctx context.Context, req *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error) {
	return c.createServer.CallUnary(ctx, req)
}

// UpdateServer calls daemon.BackendService.UpdateServer.
func (c *backendServiceClient) UpdateServer(ctx context.Context, req *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error) {
	return c.updateServer.CallUnary(ctx, req)
}

// DeleteServer calls daemon.BackendService.DeleteServer.
func (c *backendServiceClient) DeleteServer(ctx context.Context, req *connect.Request[proto_gen_go.SimpleIDMessage]) (*connect.Response[proto_gen_go.SuccessMessage], error) {
	return c.deleteServer.CallUnary(ctx, req)
}

// BackendServiceHandler is an implementation of the daemon.BackendService service.
type BackendServiceHandler interface {
	CreateServer(context.Context, *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error)
	UpdateServer(context.Context, *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error)
	DeleteServer(context.Context, *connect.Request[proto_gen_go.SimpleIDMessage]) (*connect.Response[proto_gen_go.SuccessMessage], error)
}

// NewBackendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackendServiceHandler(svc BackendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backendServiceMethods := daemon.File_daemon_Backend_proto.Services().ByName("BackendService").Methods()
	backendServiceCreateServerHandler := connect.NewUnaryHandler(
		BackendServiceCreateServerProcedure,
		svc.CreateServer,
		connect.WithSchema(backendServiceMethods.ByName("CreateServer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceUpdateServerHandler := connect.NewUnaryHandler(
		BackendServiceUpdateServerProcedure,
		svc.UpdateServer,
		connect.WithSchema(backendServiceMethods.ByName("UpdateServer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceDeleteServerHandler := connect.NewUnaryHandler(
		BackendServiceDeleteServerProcedure,
		svc.DeleteServer,
		connect.WithSchema(backendServiceMethods.ByName("DeleteServer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/daemon.BackendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackendServiceCreateServerProcedure:
			backendServiceCreateServerHandler.ServeHTTP(w, r)
		case BackendServiceUpdateServerProcedure:
			backendServiceUpdateServerHandler.ServeHTTP(w, r)
		case BackendServiceDeleteServerProcedure:
			backendServiceDeleteServerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBackendServiceHandler struct{}

func (UnimplementedBackendServiceHandler) CreateServer(context.Context, *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("daemon.BackendService.CreateServer is not implemented"))
}

func (UnimplementedBackendServiceHandler) UpdateServer(context.Context, *connect.Request[daemon.Server]) (*connect.Response[proto_gen_go.SuccessMessage], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("daemon.BackendService.UpdateServer is not implemented"))
}

func (UnimplementedBackendServiceHandler) DeleteServer(context.Context, *connect.Request[proto_gen_go.SimpleIDMessage]) (*connect.Response[proto_gen_go.SuccessMessage], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("daemon.BackendService.DeleteServer is not implemented"))
}
