// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: daemon.proto

package proto_gen_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatusType int32

const (
	ServerStatusType_SERVER_STATUS_TYPE_UNKNOWN  ServerStatusType = 0
	ServerStatusType_SERVER_STATUS_TYPE_STARTING ServerStatusType = 1
	ServerStatusType_SERVER_STATUS_TYPE_ONLINE   ServerStatusType = 2
	ServerStatusType_SERVER_STATUS_TYPE_STOPPING ServerStatusType = 3
	ServerStatusType_SERVER_STATUS_TYPE_OFFLINE  ServerStatusType = 4
)

// Enum value maps for ServerStatusType.
var (
	ServerStatusType_name = map[int32]string{
		0: "SERVER_STATUS_TYPE_UNKNOWN",
		1: "SERVER_STATUS_TYPE_STARTING",
		2: "SERVER_STATUS_TYPE_ONLINE",
		3: "SERVER_STATUS_TYPE_STOPPING",
		4: "SERVER_STATUS_TYPE_OFFLINE",
	}
	ServerStatusType_value = map[string]int32{
		"SERVER_STATUS_TYPE_UNKNOWN":  0,
		"SERVER_STATUS_TYPE_STARTING": 1,
		"SERVER_STATUS_TYPE_ONLINE":   2,
		"SERVER_STATUS_TYPE_STOPPING": 3,
		"SERVER_STATUS_TYPE_OFFLINE":  4,
	}
)

func (x ServerStatusType) Enum() *ServerStatusType {
	p := new(ServerStatusType)
	*p = x
	return p
}

func (x ServerStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[0].Descriptor()
}

func (ServerStatusType) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[0]
}

func (x ServerStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatusType.Descriptor instead.
func (ServerStatusType) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

type ServerOfflineReason int32

const (
	ServerOfflineReason_SERVER_OFFLINE_REASON_UNKNOWN ServerOfflineReason = 0
	ServerOfflineReason_SERVER_OFFLINE_REASON_CREATED ServerOfflineReason = 1
	ServerOfflineReason_SERVER_OFFLINE_REASON_STOPPED ServerOfflineReason = 2
	ServerOfflineReason_SERVER_OFFLINE_REASON_KILLED  ServerOfflineReason = 3
	ServerOfflineReason_SERVER_OFFLINE_REASON_ERROR   ServerOfflineReason = 4
)

// Enum value maps for ServerOfflineReason.
var (
	ServerOfflineReason_name = map[int32]string{
		0: "SERVER_OFFLINE_REASON_UNKNOWN",
		1: "SERVER_OFFLINE_REASON_CREATED",
		2: "SERVER_OFFLINE_REASON_STOPPED",
		3: "SERVER_OFFLINE_REASON_KILLED",
		4: "SERVER_OFFLINE_REASON_ERROR",
	}
	ServerOfflineReason_value = map[string]int32{
		"SERVER_OFFLINE_REASON_UNKNOWN": 0,
		"SERVER_OFFLINE_REASON_CREATED": 1,
		"SERVER_OFFLINE_REASON_STOPPED": 2,
		"SERVER_OFFLINE_REASON_KILLED":  3,
		"SERVER_OFFLINE_REASON_ERROR":   4,
	}
)

func (x ServerOfflineReason) Enum() *ServerOfflineReason {
	p := new(ServerOfflineReason)
	*p = x
	return p
}

func (x ServerOfflineReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerOfflineReason) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[1].Descriptor()
}

func (ServerOfflineReason) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[1]
}

func (x ServerOfflineReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerOfflineReason.Descriptor instead.
func (ServerOfflineReason) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

// Power Actions
type PowerAction int32

const (
	PowerAction_POWER_ACTION_UNSPECIFIED PowerAction = 0 // Default value, should not be used
	PowerAction_POWER_ACTION_START       PowerAction = 1
	PowerAction_POWER_ACTION_RESTART     PowerAction = 2
	PowerAction_POWER_ACTION_STOP        PowerAction = 3
	PowerAction_POWER_ACTION_KILL        PowerAction = 4
)

// Enum value maps for PowerAction.
var (
	PowerAction_name = map[int32]string{
		0: "POWER_ACTION_UNSPECIFIED",
		1: "POWER_ACTION_START",
		2: "POWER_ACTION_RESTART",
		3: "POWER_ACTION_STOP",
		4: "POWER_ACTION_KILL",
	}
	PowerAction_value = map[string]int32{
		"POWER_ACTION_UNSPECIFIED": 0,
		"POWER_ACTION_START":       1,
		"POWER_ACTION_RESTART":     2,
		"POWER_ACTION_STOP":        3,
		"POWER_ACTION_KILL":        4,
	}
)

func (x PowerAction) Enum() *PowerAction {
	p := new(PowerAction)
	*p = x
	return p
}

func (x PowerAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerAction) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[2].Descriptor()
}

func (PowerAction) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[2]
}

func (x PowerAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerAction.Descriptor instead.
func (PowerAction) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{2}
}

// Server Info
type ServerStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         ServerStatusType       `protobuf:"varint,1,opt,name=status,proto3,enum=daemon.ServerStatusType" json:"status,omitempty"`
	TimestampStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestampStart,proto3,oneof" json:"timestampStart,omitempty"`
	TimestampEnd   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestampEnd,proto3,oneof" json:"timestampEnd,omitempty"`
	OfflineReason  *ServerOfflineReason   `protobuf:"varint,4,opt,name=offlineReason,proto3,enum=daemon.ServerOfflineReason,oneof" json:"offlineReason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStatus) GetStatus() ServerStatusType {
	if x != nil {
		return x.Status
	}
	return ServerStatusType_SERVER_STATUS_TYPE_UNKNOWN
}

func (x *ServerStatus) GetTimestampStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampStart
	}
	return nil
}

func (x *ServerStatus) GetTimestampEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampEnd
	}
	return nil
}

func (x *ServerStatus) GetOfflineReason() ServerOfflineReason {
	if x != nil && x.OfflineReason != nil {
		return *x.OfflineReason
	}
	return ServerOfflineReason_SERVER_OFFLINE_REASON_UNKNOWN
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x12\x06daemon\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x02\n" +
	"\fServerStatus\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.daemon.ServerStatusTypeR\x06status\x12G\n" +
	"\x0etimestampStart\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampStart\x88\x01\x01\x12C\n" +
	"\ftimestampEnd\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\ftimestampEnd\x88\x01\x01\x12F\n" +
	"\rofflineReason\x18\x04 \x01(\x0e2\x1b.daemon.ServerOfflineReasonH\x02R\rofflineReason\x88\x01\x01B\x11\n" +
	"\x0f_timestampStartB\x0f\n" +
	"\r_timestampEndB\x10\n" +
	"\x0e_offlineReason*\xb3\x01\n" +
	"\x10ServerStatusType\x12\x1e\n" +
	"\x1aSERVER_STATUS_TYPE_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bSERVER_STATUS_TYPE_STARTING\x10\x01\x12\x1d\n" +
	"\x19SERVER_STATUS_TYPE_ONLINE\x10\x02\x12\x1f\n" +
	"\x1bSERVER_STATUS_TYPE_STOPPING\x10\x03\x12\x1e\n" +
	"\x1aSERVER_STATUS_TYPE_OFFLINE\x10\x04*\xc1\x01\n" +
	"\x13ServerOfflineReason\x12!\n" +
	"\x1dSERVER_OFFLINE_REASON_UNKNOWN\x10\x00\x12!\n" +
	"\x1dSERVER_OFFLINE_REASON_CREATED\x10\x01\x12!\n" +
	"\x1dSERVER_OFFLINE_REASON_STOPPED\x10\x02\x12 \n" +
	"\x1cSERVER_OFFLINE_REASON_KILLED\x10\x03\x12\x1f\n" +
	"\x1bSERVER_OFFLINE_REASON_ERROR\x10\x04*\x8b\x01\n" +
	"\vPowerAction\x12\x1c\n" +
	"\x18POWER_ACTION_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12POWER_ACTION_START\x10\x01\x12\x18\n" +
	"\x14POWER_ACTION_RESTART\x10\x02\x12\x15\n" +
	"\x11POWER_ACTION_STOP\x10\x03\x12\x15\n" +
	"\x11POWER_ACTION_KILL\x10\x042\xe1\x02\n" +
	"\rServerService\x12;\n" +
	"\aConsole\x12\x15.common.SimpleMessage\x1a\x15.common.SimpleMessage(\x010\x01\x122\n" +
	"\n" +
	"RunCommand\x12\x15.common.SimpleMessage\x1a\r.common.Empty\x12<\n" +
	"\bTerminal\x12\x15.common.SimpleMessage\x1a\x15.common.SimpleMessage(\x010\x01\x12:\n" +
	"\x12RunTerminalCommand\x12\x15.common.SimpleMessage\x1a\r.common.Empty\x120\n" +
	"\tGetStatus\x12\r.common.Empty\x1a\x14.daemon.ServerStatus\x123\n" +
	"\vPowerAction\x12\x15.common.SimpleMessage\x1a\r.common.EmptyB\x17Z\x15panelium/proto-gen-gob\x06proto3"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_daemon_proto_goTypes = []any{
	(ServerStatusType)(0),         // 0: daemon.ServerStatusType
	(ServerOfflineReason)(0),      // 1: daemon.ServerOfflineReason
	(PowerAction)(0),              // 2: daemon.PowerAction
	(*ServerStatus)(nil),          // 3: daemon.ServerStatus
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*SimpleMessage)(nil),         // 5: common.SimpleMessage
	(*Empty)(nil),                 // 6: common.Empty
}
var file_daemon_proto_depIdxs = []int32{
	0,  // 0: daemon.ServerStatus.status:type_name -> daemon.ServerStatusType
	4,  // 1: daemon.ServerStatus.timestampStart:type_name -> google.protobuf.Timestamp
	4,  // 2: daemon.ServerStatus.timestampEnd:type_name -> google.protobuf.Timestamp
	1,  // 3: daemon.ServerStatus.offlineReason:type_name -> daemon.ServerOfflineReason
	5,  // 4: daemon.ServerService.Console:input_type -> common.SimpleMessage
	5,  // 5: daemon.ServerService.RunCommand:input_type -> common.SimpleMessage
	5,  // 6: daemon.ServerService.Terminal:input_type -> common.SimpleMessage
	5,  // 7: daemon.ServerService.RunTerminalCommand:input_type -> common.SimpleMessage
	6,  // 8: daemon.ServerService.GetStatus:input_type -> common.Empty
	5,  // 9: daemon.ServerService.PowerAction:input_type -> common.SimpleMessage
	5,  // 10: daemon.ServerService.Console:output_type -> common.SimpleMessage
	6,  // 11: daemon.ServerService.RunCommand:output_type -> common.Empty
	5,  // 12: daemon.ServerService.Terminal:output_type -> common.SimpleMessage
	6,  // 13: daemon.ServerService.RunTerminalCommand:output_type -> common.Empty
	3,  // 14: daemon.ServerService.GetStatus:output_type -> daemon.ServerStatus
	6,  // 15: daemon.ServerService.PowerAction:output_type -> common.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	file_common_proto_init()
	file_daemon_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
