// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: daemon.proto

package proto_gen_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStatusType int32

const (
	ServerStatusType_SERVER_STATUS_UNKNOWN  ServerStatusType = 0
	ServerStatusType_SERVER_STATUS_STARTING ServerStatusType = 1
	ServerStatusType_SERVER_STATUS_ONLINE   ServerStatusType = 2
	ServerStatusType_SERVER_STATUS_STOPPING ServerStatusType = 3
	ServerStatusType_SERVER_STATUS_OFFLINE  ServerStatusType = 4
)

// Enum value maps for ServerStatusType.
var (
	ServerStatusType_name = map[int32]string{
		0: "SERVER_STATUS_UNKNOWN",
		1: "SERVER_STATUS_STARTING",
		2: "SERVER_STATUS_ONLINE",
		3: "SERVER_STATUS_STOPPING",
		4: "SERVER_STATUS_OFFLINE",
	}
	ServerStatusType_value = map[string]int32{
		"SERVER_STATUS_UNKNOWN":  0,
		"SERVER_STATUS_STARTING": 1,
		"SERVER_STATUS_ONLINE":   2,
		"SERVER_STATUS_STOPPING": 3,
		"SERVER_STATUS_OFFLINE":  4,
	}
)

func (x ServerStatusType) Enum() *ServerStatusType {
	p := new(ServerStatusType)
	*p = x
	return p
}

func (x ServerStatusType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatusType) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[0].Descriptor()
}

func (ServerStatusType) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[0]
}

func (x ServerStatusType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ServerStatusType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ServerStatusType(num)
	return nil
}

// Deprecated: Use ServerStatusType.Descriptor instead.
func (ServerStatusType) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

type ServerOfflineReason int32

const (
	ServerOfflineReason_SERVER_OFFLINE_REASON_UNKNOWN ServerOfflineReason = 0
	ServerOfflineReason_SERVER_OFFLINE_REASON_CREATED ServerOfflineReason = 1
	ServerOfflineReason_SERVER_OFFLINE_REASON_STOPPED ServerOfflineReason = 2
	ServerOfflineReason_SERVER_OFFLINE_REASON_KILLED  ServerOfflineReason = 3
	ServerOfflineReason_SERVER_OFFLINE_REASON_ERROR   ServerOfflineReason = 4
)

// Enum value maps for ServerOfflineReason.
var (
	ServerOfflineReason_name = map[int32]string{
		0: "SERVER_OFFLINE_REASON_UNKNOWN",
		1: "SERVER_OFFLINE_REASON_CREATED",
		2: "SERVER_OFFLINE_REASON_STOPPED",
		3: "SERVER_OFFLINE_REASON_KILLED",
		4: "SERVER_OFFLINE_REASON_ERROR",
	}
	ServerOfflineReason_value = map[string]int32{
		"SERVER_OFFLINE_REASON_UNKNOWN": 0,
		"SERVER_OFFLINE_REASON_CREATED": 1,
		"SERVER_OFFLINE_REASON_STOPPED": 2,
		"SERVER_OFFLINE_REASON_KILLED":  3,
		"SERVER_OFFLINE_REASON_ERROR":   4,
	}
)

func (x ServerOfflineReason) Enum() *ServerOfflineReason {
	p := new(ServerOfflineReason)
	*p = x
	return p
}

func (x ServerOfflineReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerOfflineReason) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_proto_enumTypes[1].Descriptor()
}

func (ServerOfflineReason) Type() protoreflect.EnumType {
	return &file_daemon_proto_enumTypes[1]
}

func (x ServerOfflineReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ServerOfflineReason) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ServerOfflineReason(num)
	return nil
}

// Deprecated: Use ServerOfflineReason.Descriptor instead.
func (ServerOfflineReason) EnumDescriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{1}
}

// Server Info
type ServerStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         *ServerStatusType      `protobuf:"varint,1,req,name=status,enum=ServerStatusType" json:"status,omitempty"`
	TimestampStart *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestampStart" json:"timestampStart,omitempty"`
	TimestampEnd   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestampEnd" json:"timestampEnd,omitempty"`
	OfflineReason  *ServerOfflineReason   `protobuf:"varint,4,opt,name=offlineReason,enum=ServerOfflineReason" json:"offlineReason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_daemon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_daemon_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStatus) GetStatus() ServerStatusType {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ServerStatusType_SERVER_STATUS_UNKNOWN
}

func (x *ServerStatus) GetTimestampStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampStart
	}
	return nil
}

func (x *ServerStatus) GetTimestampEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampEnd
	}
	return nil
}

func (x *ServerStatus) GetOfflineReason() ServerOfflineReason {
	if x != nil && x.OfflineReason != nil {
		return *x.OfflineReason
	}
	return ServerOfflineReason_SERVER_OFFLINE_REASON_UNKNOWN
}

var File_daemon_proto protoreflect.FileDescriptor

const file_daemon_proto_rawDesc = "" +
	"\n" +
	"\fdaemon.proto\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n" +
	"\fServerStatus\x12)\n" +
	"\x06status\x18\x01 \x02(\x0e2\x11.ServerStatusTypeR\x06status\x12B\n" +
	"\x0etimestampStart\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampStart\x12>\n" +
	"\ftimestampEnd\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ftimestampEnd\x12:\n" +
	"\rofflineReason\x18\x04 \x01(\x0e2\x14.ServerOfflineReasonR\rofflineReason*\x9a\x01\n" +
	"\x10ServerStatusType\x12\x19\n" +
	"\x15SERVER_STATUS_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16SERVER_STATUS_STARTING\x10\x01\x12\x18\n" +
	"\x14SERVER_STATUS_ONLINE\x10\x02\x12\x1a\n" +
	"\x16SERVER_STATUS_STOPPING\x10\x03\x12\x19\n" +
	"\x15SERVER_STATUS_OFFLINE\x10\x04*\xc1\x01\n" +
	"\x13ServerOfflineReason\x12!\n" +
	"\x1dSERVER_OFFLINE_REASON_UNKNOWN\x10\x00\x12!\n" +
	"\x1dSERVER_OFFLINE_REASON_CREATED\x10\x01\x12!\n" +
	"\x1dSERVER_OFFLINE_REASON_STOPPED\x10\x02\x12 \n" +
	"\x1cSERVER_OFFLINE_REASON_KILLED\x10\x03\x12\x1f\n" +
	"\x1bSERVER_OFFLINE_REASON_ERROR\x10\x042\xca\x02\n" +
	"\rServerService\x12-\n" +
	"\aConsole\x12\x0e.SimpleMessage\x1a\x0e.SimpleMessage(\x010\x01\x12$\n" +
	"\n" +
	"RunCommand\x12\x0e.SimpleMessage\x1a\x06.Empty\x12.\n" +
	"\bTerminal\x12\x0e.SimpleMessage\x1a\x0e.SimpleMessage(\x010\x01\x12,\n" +
	"\x12RunTerminalCommand\x12\x0e.SimpleMessage\x1a\x06.Empty\x12\"\n" +
	"\tGetStatus\x12\x06.Empty\x1a\r.ServerStatus\x12\x17\n" +
	"\x05Start\x12\x06.Empty\x1a\x06.Empty\x12\x19\n" +
	"\aRestart\x12\x06.Empty\x1a\x06.Empty\x12\x16\n" +
	"\x04Stop\x12\x06.Empty\x1a\x06.Empty\x12\x16\n" +
	"\x04Kill\x12\x06.Empty\x1a\x06.EmptyB\x17Z\x15panelium/proto-gen-go"

var (
	file_daemon_proto_rawDescOnce sync.Once
	file_daemon_proto_rawDescData []byte
)

func file_daemon_proto_rawDescGZIP() []byte {
	file_daemon_proto_rawDescOnce.Do(func() {
		file_daemon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)))
	})
	return file_daemon_proto_rawDescData
}

var file_daemon_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_daemon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_daemon_proto_goTypes = []any{
	(ServerStatusType)(0),         // 0: ServerStatusType
	(ServerOfflineReason)(0),      // 1: ServerOfflineReason
	(*ServerStatus)(nil),          // 2: ServerStatus
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*SimpleMessage)(nil),         // 4: SimpleMessage
	(*Empty)(nil),                 // 5: Empty
}
var file_daemon_proto_depIdxs = []int32{
	0,  // 0: ServerStatus.status:type_name -> ServerStatusType
	3,  // 1: ServerStatus.timestampStart:type_name -> google.protobuf.Timestamp
	3,  // 2: ServerStatus.timestampEnd:type_name -> google.protobuf.Timestamp
	1,  // 3: ServerStatus.offlineReason:type_name -> ServerOfflineReason
	4,  // 4: ServerService.Console:input_type -> SimpleMessage
	4,  // 5: ServerService.RunCommand:input_type -> SimpleMessage
	4,  // 6: ServerService.Terminal:input_type -> SimpleMessage
	4,  // 7: ServerService.RunTerminalCommand:input_type -> SimpleMessage
	5,  // 8: ServerService.GetStatus:input_type -> Empty
	5,  // 9: ServerService.Start:input_type -> Empty
	5,  // 10: ServerService.Restart:input_type -> Empty
	5,  // 11: ServerService.Stop:input_type -> Empty
	5,  // 12: ServerService.Kill:input_type -> Empty
	4,  // 13: ServerService.Console:output_type -> SimpleMessage
	5,  // 14: ServerService.RunCommand:output_type -> Empty
	4,  // 15: ServerService.Terminal:output_type -> SimpleMessage
	5,  // 16: ServerService.RunTerminalCommand:output_type -> Empty
	2,  // 17: ServerService.GetStatus:output_type -> ServerStatus
	5,  // 18: ServerService.Start:output_type -> Empty
	5,  // 19: ServerService.Restart:output_type -> Empty
	5,  // 20: ServerService.Stop:output_type -> Empty
	5,  // 21: ServerService.Kill:output_type -> Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_daemon_proto_init() }
func file_daemon_proto_init() {
	if File_daemon_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_proto_rawDesc), len(file_daemon_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_proto_goTypes,
		DependencyIndexes: file_daemon_proto_depIdxs,
		EnumInfos:         file_daemon_proto_enumTypes,
		MessageInfos:      file_daemon_proto_msgTypes,
	}.Build()
	File_daemon_proto = out.File
	file_daemon_proto_goTypes = nil
	file_daemon_proto_depIdxs = nil
}
