// @generated by protoc-gen-es v2.5.0 with parameter "target=ts,import_extension=none,js_import_style=module"
// @generated from file daemon/Internal.proto (package daemon, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { SuccessMessageSchema } from "../common_pb";
import { file_common } from "../common_pb";
import type { Allocation, ResourceLimit } from "./Server_pb";
import { file_daemon_Server } from "./Server_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file daemon/Internal.proto.
 */
export const file_daemon_Internal: GenFile = /*@__PURE__*/
  fileDesc("ChVkYWVtb24vSW50ZXJuYWwucHJvdG8SBmRhZW1vbiLKAQoTQ3JlYXRlU2VydmVyUmVxdWVzdBIQCghzZXJ2ZXJJZBgBIAEoCRIPCgdvd25lcklkGAIgASgJEg8KB3VzZXJJZHMYAyADKAkSJwoLYWxsb2NhdGlvbnMYBCADKAsyEi5kYWVtb24uQWxsb2NhdGlvbhIsCg1yZXNvdXJjZUxpbWl0GAUgASgLMhUuZGFlbW9uLlJlc291cmNlTGltaXQSEwoLYmx1ZXByaW50SWQYBiABKAkSEwoLZG9ja2VySW1hZ2UYByABKAki+gEKE1VwZGF0ZVNlcnZlclJlcXVlc3QSEAoIc2VydmVySWQYASABKAkSDwoHdXNlcklkcxgDIAMoCRInCgthbGxvY2F0aW9ucxgEIAMoCzISLmRhZW1vbi5BbGxvY2F0aW9uEjEKDXJlc291cmNlTGltaXQYBSABKAsyFS5kYWVtb24uUmVzb3VyY2VMaW1pdEgAiAEBEhgKC2JsdWVwcmludElkGAYgASgJSAGIAQESGAoLZG9ja2VySW1hZ2UYByABKAlIAogBAUIQCg5fcmVzb3VyY2VMaW1pdEIOCgxfYmx1ZXByaW50SWRCDgoMX2RvY2tlckltYWdlIjYKE0RlbGV0ZVNlcnZlclJlcXVlc3QSEAoIc2VydmVySWQYASABKAkSDQoFZm9yY2UYAiABKAgy4AEKD0ludGVybmFsU2VydmljZRJDCgxDcmVhdGVTZXJ2ZXISGy5kYWVtb24uQ3JlYXRlU2VydmVyUmVxdWVzdBoWLmNvbW1vbi5TdWNjZXNzTWVzc2FnZRJDCgxVcGRhdGVTZXJ2ZXISGy5kYWVtb24uVXBkYXRlU2VydmVyUmVxdWVzdBoWLmNvbW1vbi5TdWNjZXNzTWVzc2FnZRJDCgxEZWxldGVTZXJ2ZXISGy5kYWVtb24uRGVsZXRlU2VydmVyUmVxdWVzdBoWLmNvbW1vbi5TdWNjZXNzTWVzc2FnZUIeWhxwYW5lbGl1bS9wcm90b19nZW5fZ28vZGFlbW9uYgZwcm90bzM", [file_common, file_daemon_Server]);

/**
 * @generated from message daemon.CreateServerRequest
 */
export type CreateServerRequest = Message<"daemon.CreateServerRequest"> & {
  /**
   * @generated from field: string serverId = 1;
   */
  serverId: string;

  /**
   * @generated from field: string ownerId = 2;
   */
  ownerId: string;

  /**
   * @generated from field: repeated string userIds = 3;
   */
  userIds: string[];

  /**
   * @generated from field: repeated daemon.Allocation allocations = 4;
   */
  allocations: Allocation[];

  /**
   * @generated from field: daemon.ResourceLimit resourceLimit = 5;
   */
  resourceLimit?: ResourceLimit;

  /**
   * @generated from field: string blueprintId = 6;
   */
  blueprintId: string;

  /**
   * @generated from field: string dockerImage = 7;
   */
  dockerImage: string;
};

/**
 * Describes the message daemon.CreateServerRequest.
 * Use `create(CreateServerRequestSchema)` to create a new message.
 */
export const CreateServerRequestSchema: GenMessage<CreateServerRequest> = /*@__PURE__*/
  messageDesc(file_daemon_Internal, 0);

/**
 * TODO: this should probably instead be pulled from backend on server startup
 *
 * @generated from message daemon.UpdateServerRequest
 */
export type UpdateServerRequest = Message<"daemon.UpdateServerRequest"> & {
  /**
   * @generated from field: string serverId = 1;
   */
  serverId: string;

  /**
   * optional
   *
   * @generated from field: repeated string userIds = 3;
   */
  userIds: string[];

  /**
   * optional
   *
   * @generated from field: repeated daemon.Allocation allocations = 4;
   */
  allocations: Allocation[];

  /**
   * @generated from field: optional daemon.ResourceLimit resourceLimit = 5;
   */
  resourceLimit?: ResourceLimit;

  /**
   * @generated from field: optional string blueprintId = 6;
   */
  blueprintId?: string;

  /**
   * @generated from field: optional string dockerImage = 7;
   */
  dockerImage?: string;
};

/**
 * Describes the message daemon.UpdateServerRequest.
 * Use `create(UpdateServerRequestSchema)` to create a new message.
 */
export const UpdateServerRequestSchema: GenMessage<UpdateServerRequest> = /*@__PURE__*/
  messageDesc(file_daemon_Internal, 1);

/**
 * @generated from message daemon.DeleteServerRequest
 */
export type DeleteServerRequest = Message<"daemon.DeleteServerRequest"> & {
  /**
   * @generated from field: string serverId = 1;
   */
  serverId: string;

  /**
   * @generated from field: bool force = 2;
   */
  force: boolean;
};

/**
 * Describes the message daemon.DeleteServerRequest.
 * Use `create(DeleteServerRequestSchema)` to create a new message.
 */
export const DeleteServerRequestSchema: GenMessage<DeleteServerRequest> = /*@__PURE__*/
  messageDesc(file_daemon_Internal, 2);

/**
 * @generated from service daemon.InternalService
 */
export const InternalService: GenService<{
  /**
   * @generated from rpc daemon.InternalService.CreateServer
   */
  createServer: {
    methodKind: "unary";
    input: typeof CreateServerRequestSchema;
    output: typeof SuccessMessageSchema;
  },
  /**
   * @generated from rpc daemon.InternalService.UpdateServer
   */
  updateServer: {
    methodKind: "unary";
    input: typeof UpdateServerRequestSchema;
    output: typeof SuccessMessageSchema;
  },
  /**
   * @generated from rpc daemon.InternalService.DeleteServer
   */
  deleteServer: {
    methodKind: "unary";
    input: typeof DeleteServerRequestSchema;
    output: typeof SuccessMessageSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_daemon_Internal, 0);

