openapi: 3.1.0
info:
  title: common
paths: {}
components:
  schemas:
    common.Empty:
      type: object
      title: Empty
      additionalProperties: false
    common.IDMessage:
      type: object
      properties:
        id:
          type: string
          title: id
        text:
          type: string
          title: text
      title: IDMessage
      additionalProperties: false
    common.IPAllocation:
      type: object
      properties:
        ip:
          type: string
          title: ip
        port:
          type: integer
          title: port
          description: MUST BE 1024-65535
      title: IPAllocation
      additionalProperties: false
    common.ResourceLimit:
      type: object
      properties:
        cpu:
          type: integer
          title: cpu
          description: CPU in percentage (100% = 1 vCore)
        ram:
          type: integer
          title: ram
          description: RAM in MB
        swap:
          type: integer
          title: swap
          description: SWAP in MB
        storage:
          type: integer
          title: storage
          description: Storage in MB
      title: ResourceLimit
      additionalProperties: false
    common.SimpleIDMessage:
      type: object
      properties:
        id:
          type: string
          title: id
      title: SimpleIDMessage
      additionalProperties: false
    common.SimpleMessage:
      type: object
      properties:
        text:
          type: string
          title: text
      title: SimpleMessage
      additionalProperties: false
    common.StreamIDMessage:
      type: object
      properties:
        id:
          type: string
          title: id
          description: only required for the first message in the stream, subsequent messages can omit this field
          nullable: true
        text:
          type: string
          title: text
          description: required after the first message in the stream, first message can omit this field
          nullable: true
      title: StreamIDMessage
      additionalProperties: false
    common.SuccessMessage:
      type: object
      properties:
        success:
          type: boolean
          title: success
      title: SuccessMessage
      additionalProperties: false
security: []
