openapi: 3.1.0
info:
  title: common
paths: {}
components:
  schemas:
    common.Empty:
      type: object
      title: Empty
      additionalProperties: false
    common.SimpleMessage:
      type: object
      properties:
        text:
          type: string
          title: text
      title: SimpleMessage
      additionalProperties: false
security: []
