openapi: 3.1.0
info: {}
paths: {}
components:
  schemas:
    Empty:
      type: object
      title: Empty
      additionalProperties: false
    SimpleMessage:
      type: object
      properties:
        text:
          type: string
          title: text
      title: SimpleMessage
      additionalProperties: false
security: []
