openapi: 3.1.0
info:
  title: common
paths: {}
components:
  schemas:
    common.Empty:
      type: object
      title: Empty
      additionalProperties: false
    common.IDMessage:
      type: object
      properties:
        id:
          type: string
          title: id
        text:
          type: string
          title: text
      title: IDMessage
      additionalProperties: false
    common.IPAllocation:
      type: object
      properties:
        ip:
          type: string
          title: ip
        port:
          type: integer
          title: port
          description: MUST BE 1024-65535
      title: IPAllocation
      additionalProperties: false
    common.Pagination:
      type: object
      properties:
        page:
          type: integer
          title: page
        pageSize:
          type: integer
          title: page_size
        total:
          type: integer
          title: total
          nullable: true
      title: Pagination
      additionalProperties: false
    common.ResourceLimit:
      type: object
      properties:
        cpu:
          type: integer
          title: cpu
          description: CPU in percentage (100% = 1 vCore)
        ram:
          type: integer
          title: ram
          description: RAM in MB
        swap:
          type: integer
          title: swap
          description: SWAP in MB
        storage:
          type: integer
          title: storage
          description: Storage in MB
      title: ResourceLimit
      additionalProperties: false
    common.ResourceUsage:
      type: object
      properties:
        cpu:
          type: number
          title: cpu
          format: float
          description: CPU in percentage (100% = 1 vCore)
        ram:
          type: number
          title: ram
          format: float
          description: RAM in MB
        storage:
          type: number
          title: storage
          format: float
          description: Storage in MB
      title: ResourceUsage
      additionalProperties: false
    common.SimpleIDMessage:
      type: object
      properties:
        id:
          type: string
          title: id
      title: SimpleIDMessage
      additionalProperties: false
    common.SimpleMessage:
      type: object
      properties:
        text:
          type: string
          title: text
      title: SimpleMessage
      additionalProperties: false
    common.SuccessMessage:
      type: object
      properties:
        success:
          type: boolean
          title: success
      title: SuccessMessage
      additionalProperties: false
security: []
