name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2404
    strategy:
      matrix:
        target: [backend, daemon, dashboard]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ${{ matrix.target }}
        uses: useblacksmith/build-push-action@v1
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.target }}
          push: true
          tags: ghcr.io/panelium/${{ matrix.target }}:latest
