name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/backend:latest

      - name: Build and push daemon
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: daemon
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/daemon:latest

      - name: Build and push dashboard
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: dashboard
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dashboard:latest